# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  adguard-exporter = {
    pname = "adguard-exporter";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "henrywhitaker3";
      repo = "adguard-exporter";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-OltYzxBOOcaW3oYNFvxxjG1qRvuLaZfReSeQaNGiRDc=";
    };
  };
  chrony-exporter = {
    pname = "chrony-exporter";
    version = "v0.13.3";
    src = fetchFromGitHub {
      owner = "SuperQ";
      repo = "chrony_exporter";
      rev = "v0.13.3";
      fetchSubmodules = false;
      sha256 = "sha256-szrqxXo8hqc7fjDDGOjyJ6JGV3LBWPkkMXGw7mSXpY8=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "29eef5515a1e5e21ece02604198da6f724a14f85";
    src = fetchFromGitHub {
      owner = "cockpit-project";
      repo = "cockpit-podman";
      rev = "29eef5515a1e5e21ece02604198da6f724a14f85";
      fetchSubmodules = false;
      sha256 = "sha256-SkZb8NcN8iSocVpdg4Y8KWNKfyBKn6HhYSO7kIcjxHw=";
    };
    date = "2026-03-17";
  };
  flux-local = {
    pname = "flux-local";
    version = "8.1.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/f/flux_local/flux_local-8.1.0.tar.gz";
      sha256 = "sha256-MotQ07wf/GQ3PsUrPU32I9bZ+Dti4D1nddBkDyu8k9I=";
    };
  };
  gpsd-prometheus-exporter = {
    pname = "gpsd-prometheus-exporter";
    version = "192050aeb24db92abe5e3229cdbca9199c6b9c42";
    src = fetchFromGitHub {
      owner = "brendanbank";
      repo = "gpsd-prometheus-exporter";
      rev = "192050aeb24db92abe5e3229cdbca9199c6b9c42";
      fetchSubmodules = false;
      sha256 = "sha256-qDBwjzl/4EwKfMoaFKdFUHl9VK4PTFZCXTitH9UlEKE=";
    };
    date = "2026-03-10";
  };
  mqtt-explorer = {
    pname = "mqtt-explorer";
    version = "v0.3.5";
    src = fetchFromGitHub {
      owner = "thomasnordquist";
      repo = "MQTT-Explorer";
      rev = "v0.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-lXHPKOZh5gbG+kpH9wLBcHztS7fBj9D57ySKd1xkhxc=";
    };
  };
  npiperelay = {
    pname = "npiperelay";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "jstarks";
      repo = "npiperelay";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-cg4aZmpTysc8m1euxIO2XPv8OMnBk1DwhFcuIFHF/1o=";
    };
  };
  talosctl = {
    pname = "talosctl";
    version = "v1.12.5";
    src = fetchFromGitHub {
      owner = "siderolabs";
      repo = "talos";
      rev = "v1.12.5";
      fetchSubmodules = false;
      sha256 = "sha256-mGfaf64he6/eK8JMHOCUSKaAEnsxoceYWDHhsD8WQ9Q=";
    };
  };
}
