# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  adguard-exporter = {
    pname = "adguard-exporter";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "henrywhitaker3";
      repo = "adguard-exporter";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-OltYzxBOOcaW3oYNFvxxjG1qRvuLaZfReSeQaNGiRDc=";
    };
  };
  chrony-exporter = {
    pname = "chrony-exporter";
    version = "v0.12.3";
    src = fetchFromGitHub {
      owner = "SuperQ";
      repo = "chrony_exporter";
      rev = "v0.12.3";
      fetchSubmodules = false;
      sha256 = "sha256-uPKSobrDczaDH82tl/57aB3QUycsqOxTW2Jxt0s5spk=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "39f66bbe9d35cc706939a778ab2d2a49782bb191";
    src = fetchFromGitHub {
      owner = "cockpit-project";
      repo = "cockpit-podman";
      rev = "39f66bbe9d35cc706939a778ab2d2a49782bb191";
      fetchSubmodules = false;
      sha256 = "sha256-HradUs4a0XcvxGeI7b4WaFmJIuuzS6Eoxiy5n1l7q1w=";
    };
    date = "2026-02-19";
  };
  flux-local = {
    pname = "flux-local";
    version = "8.1.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/f/flux_local/flux_local-8.1.0.tar.gz";
      sha256 = "sha256-MotQ07wf/GQ3PsUrPU32I9bZ+Dti4D1nddBkDyu8k9I=";
    };
  };
  gpsd-prometheus-exporter = {
    pname = "gpsd-prometheus-exporter";
    version = "4a96cb6c74f20c62f474acb884173488ee6e7716";
    src = fetchFromGitHub {
      owner = "brendanbank";
      repo = "gpsd-prometheus-exporter";
      rev = "4a96cb6c74f20c62f474acb884173488ee6e7716";
      fetchSubmodules = false;
      sha256 = "sha256-o3HMYvAgZsFDBpe20sQo2HgUReAb0TFFubXINMVpOqE=";
    };
    date = "2026-02-15";
  };
  mqtt-explorer = {
    pname = "mqtt-explorer";
    version = "v0.3.5";
    src = fetchFromGitHub {
      owner = "thomasnordquist";
      repo = "MQTT-Explorer";
      rev = "v0.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-lXHPKOZh5gbG+kpH9wLBcHztS7fBj9D57ySKd1xkhxc=";
    };
  };
  npiperelay = {
    pname = "npiperelay";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "jstarks";
      repo = "npiperelay";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-cg4aZmpTysc8m1euxIO2XPv8OMnBk1DwhFcuIFHF/1o=";
    };
  };
  talosctl = {
    pname = "talosctl";
    version = "v1.12.4";
    src = fetchFromGitHub {
      owner = "siderolabs";
      repo = "talos";
      rev = "v1.12.4";
      fetchSubmodules = false;
      sha256 = "sha256-shXNd8Vz5YXpA9J6m4IDsRx8cTR7ZDPDfjm8kVssBqg=";
    };
  };
}
